# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Gebruiker/Desktop/C++/psvita/uMario_Vita/uMario-PSVita-Port

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Gebruiker/Desktop/C++/psvita/uMario_Vita/uMario-PSVita-Port

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Gebruiker/Desktop/C++/psvita/uMario_Vita/uMario-PSVita-Port/CMakeFiles /mnt/c/Users/Gebruiker/Desktop/C++/psvita/uMario_Vita/uMario-PSVita-Port/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Gebruiker/Desktop/C++/psvita/uMario_Vita/uMario-PSVita-Port/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uMario.vpk

# Build rule for target.
uMario.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uMario.vpk
.PHONY : uMario.vpk

# fast build rule for target.
uMario.vpk/fast:
	$(MAKE) -f CMakeFiles/uMario.vpk.dir/build.make CMakeFiles/uMario.vpk.dir/build
.PHONY : uMario.vpk/fast

#=============================================================================
# Target rules for targets named uMario.self

# Build rule for target.
uMario.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uMario.self
.PHONY : uMario.self

# fast build rule for target.
uMario.self/fast:
	$(MAKE) -f CMakeFiles/uMario.self.dir/build.make CMakeFiles/uMario.self.dir/build
.PHONY : uMario.self/fast

#=============================================================================
# Target rules for targets named uMario

# Build rule for target.
uMario: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uMario
.PHONY : uMario

# fast build rule for target.
uMario/fast:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/build
.PHONY : uMario/fast

uNext/AboutMenu.obj: uNext/AboutMenu.cpp.obj

.PHONY : uNext/AboutMenu.obj

# target to build an object file
uNext/AboutMenu.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/AboutMenu.cpp.obj
.PHONY : uNext/AboutMenu.cpp.obj

uNext/AboutMenu.i: uNext/AboutMenu.cpp.i

.PHONY : uNext/AboutMenu.i

# target to preprocess a source file
uNext/AboutMenu.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/AboutMenu.cpp.i
.PHONY : uNext/AboutMenu.cpp.i

uNext/AboutMenu.s: uNext/AboutMenu.cpp.s

.PHONY : uNext/AboutMenu.s

# target to generate assembly for a file
uNext/AboutMenu.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/AboutMenu.cpp.s
.PHONY : uNext/AboutMenu.cpp.s

uNext/Beetle.obj: uNext/Beetle.cpp.obj

.PHONY : uNext/Beetle.obj

# target to build an object file
uNext/Beetle.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Beetle.cpp.obj
.PHONY : uNext/Beetle.cpp.obj

uNext/Beetle.i: uNext/Beetle.cpp.i

.PHONY : uNext/Beetle.i

# target to preprocess a source file
uNext/Beetle.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Beetle.cpp.i
.PHONY : uNext/Beetle.cpp.i

uNext/Beetle.s: uNext/Beetle.cpp.s

.PHONY : uNext/Beetle.s

# target to generate assembly for a file
uNext/Beetle.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Beetle.cpp.s
.PHONY : uNext/Beetle.cpp.s

uNext/Block.obj: uNext/Block.cpp.obj

.PHONY : uNext/Block.obj

# target to build an object file
uNext/Block.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Block.cpp.obj
.PHONY : uNext/Block.cpp.obj

uNext/Block.i: uNext/Block.cpp.i

.PHONY : uNext/Block.i

# target to preprocess a source file
uNext/Block.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Block.cpp.i
.PHONY : uNext/Block.cpp.i

uNext/Block.s: uNext/Block.cpp.s

.PHONY : uNext/Block.s

# target to generate assembly for a file
uNext/Block.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Block.cpp.s
.PHONY : uNext/Block.cpp.s

uNext/BlockDebris.obj: uNext/BlockDebris.cpp.obj

.PHONY : uNext/BlockDebris.obj

# target to build an object file
uNext/BlockDebris.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BlockDebris.cpp.obj
.PHONY : uNext/BlockDebris.cpp.obj

uNext/BlockDebris.i: uNext/BlockDebris.cpp.i

.PHONY : uNext/BlockDebris.i

# target to preprocess a source file
uNext/BlockDebris.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BlockDebris.cpp.i
.PHONY : uNext/BlockDebris.cpp.i

uNext/BlockDebris.s: uNext/BlockDebris.cpp.s

.PHONY : uNext/BlockDebris.s

# target to generate assembly for a file
uNext/BlockDebris.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BlockDebris.cpp.s
.PHONY : uNext/BlockDebris.cpp.s

uNext/Bowser.obj: uNext/Bowser.cpp.obj

.PHONY : uNext/Bowser.obj

# target to build an object file
uNext/Bowser.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Bowser.cpp.obj
.PHONY : uNext/Bowser.cpp.obj

uNext/Bowser.i: uNext/Bowser.cpp.i

.PHONY : uNext/Bowser.i

# target to preprocess a source file
uNext/Bowser.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Bowser.cpp.i
.PHONY : uNext/Bowser.cpp.i

uNext/Bowser.s: uNext/Bowser.cpp.s

.PHONY : uNext/Bowser.s

# target to generate assembly for a file
uNext/Bowser.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Bowser.cpp.s
.PHONY : uNext/Bowser.cpp.s

uNext/Bubble.obj: uNext/Bubble.cpp.obj

.PHONY : uNext/Bubble.obj

# target to build an object file
uNext/Bubble.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Bubble.cpp.obj
.PHONY : uNext/Bubble.cpp.obj

uNext/Bubble.i: uNext/Bubble.cpp.i

.PHONY : uNext/Bubble.i

# target to preprocess a source file
uNext/Bubble.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Bubble.cpp.i
.PHONY : uNext/Bubble.cpp.i

uNext/Bubble.s: uNext/Bubble.cpp.s

.PHONY : uNext/Bubble.s

# target to generate assembly for a file
uNext/Bubble.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Bubble.cpp.s
.PHONY : uNext/Bubble.cpp.s

uNext/BulletBill.obj: uNext/BulletBill.cpp.obj

.PHONY : uNext/BulletBill.obj

# target to build an object file
uNext/BulletBill.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BulletBill.cpp.obj
.PHONY : uNext/BulletBill.cpp.obj

uNext/BulletBill.i: uNext/BulletBill.cpp.i

.PHONY : uNext/BulletBill.i

# target to preprocess a source file
uNext/BulletBill.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BulletBill.cpp.i
.PHONY : uNext/BulletBill.cpp.i

uNext/BulletBill.s: uNext/BulletBill.cpp.s

.PHONY : uNext/BulletBill.s

# target to generate assembly for a file
uNext/BulletBill.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BulletBill.cpp.s
.PHONY : uNext/BulletBill.cpp.s

uNext/BulletBillSpawner.obj: uNext/BulletBillSpawner.cpp.obj

.PHONY : uNext/BulletBillSpawner.obj

# target to build an object file
uNext/BulletBillSpawner.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BulletBillSpawner.cpp.obj
.PHONY : uNext/BulletBillSpawner.cpp.obj

uNext/BulletBillSpawner.i: uNext/BulletBillSpawner.cpp.i

.PHONY : uNext/BulletBillSpawner.i

# target to preprocess a source file
uNext/BulletBillSpawner.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BulletBillSpawner.cpp.i
.PHONY : uNext/BulletBillSpawner.cpp.i

uNext/BulletBillSpawner.s: uNext/BulletBillSpawner.cpp.s

.PHONY : uNext/BulletBillSpawner.s

# target to generate assembly for a file
uNext/BulletBillSpawner.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/BulletBillSpawner.cpp.s
.PHONY : uNext/BulletBillSpawner.cpp.s

uNext/CFG.obj: uNext/CFG.cpp.obj

.PHONY : uNext/CFG.obj

# target to build an object file
uNext/CFG.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/CFG.cpp.obj
.PHONY : uNext/CFG.cpp.obj

uNext/CFG.i: uNext/CFG.cpp.i

.PHONY : uNext/CFG.i

# target to preprocess a source file
uNext/CFG.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/CFG.cpp.i
.PHONY : uNext/CFG.cpp.i

uNext/CFG.s: uNext/CFG.cpp.s

.PHONY : uNext/CFG.s

# target to generate assembly for a file
uNext/CFG.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/CFG.cpp.s
.PHONY : uNext/CFG.cpp.s

uNext/Cheep.obj: uNext/Cheep.cpp.obj

.PHONY : uNext/Cheep.obj

# target to build an object file
uNext/Cheep.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Cheep.cpp.obj
.PHONY : uNext/Cheep.cpp.obj

uNext/Cheep.i: uNext/Cheep.cpp.i

.PHONY : uNext/Cheep.i

# target to preprocess a source file
uNext/Cheep.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Cheep.cpp.i
.PHONY : uNext/Cheep.cpp.i

uNext/Cheep.s: uNext/Cheep.cpp.s

.PHONY : uNext/Cheep.s

# target to generate assembly for a file
uNext/Cheep.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Cheep.cpp.s
.PHONY : uNext/Cheep.cpp.s

uNext/CheepSpawner.obj: uNext/CheepSpawner.cpp.obj

.PHONY : uNext/CheepSpawner.obj

# target to build an object file
uNext/CheepSpawner.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/CheepSpawner.cpp.obj
.PHONY : uNext/CheepSpawner.cpp.obj

uNext/CheepSpawner.i: uNext/CheepSpawner.cpp.i

.PHONY : uNext/CheepSpawner.i

# target to preprocess a source file
uNext/CheepSpawner.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/CheepSpawner.cpp.i
.PHONY : uNext/CheepSpawner.cpp.i

uNext/CheepSpawner.s: uNext/CheepSpawner.cpp.s

.PHONY : uNext/CheepSpawner.s

# target to generate assembly for a file
uNext/CheepSpawner.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/CheepSpawner.cpp.s
.PHONY : uNext/CheepSpawner.cpp.s

uNext/Coin.obj: uNext/Coin.cpp.obj

.PHONY : uNext/Coin.obj

# target to build an object file
uNext/Coin.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Coin.cpp.obj
.PHONY : uNext/Coin.cpp.obj

uNext/Coin.i: uNext/Coin.cpp.i

.PHONY : uNext/Coin.i

# target to preprocess a source file
uNext/Coin.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Coin.cpp.i
.PHONY : uNext/Coin.cpp.i

uNext/Coin.s: uNext/Coin.cpp.s

.PHONY : uNext/Coin.s

# target to generate assembly for a file
uNext/Coin.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Coin.cpp.s
.PHONY : uNext/Coin.cpp.s

uNext/Console.obj: uNext/Console.cpp.obj

.PHONY : uNext/Console.obj

# target to build an object file
uNext/Console.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Console.cpp.obj
.PHONY : uNext/Console.cpp.obj

uNext/Console.i: uNext/Console.cpp.i

.PHONY : uNext/Console.i

# target to preprocess a source file
uNext/Console.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Console.cpp.i
.PHONY : uNext/Console.cpp.i

uNext/Console.s: uNext/Console.cpp.s

.PHONY : uNext/Console.s

# target to generate assembly for a file
uNext/Console.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Console.cpp.s
.PHONY : uNext/Console.cpp.s

uNext/Core.obj: uNext/Core.cpp.obj

.PHONY : uNext/Core.obj

# target to build an object file
uNext/Core.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Core.cpp.obj
.PHONY : uNext/Core.cpp.obj

uNext/Core.i: uNext/Core.cpp.i

.PHONY : uNext/Core.i

# target to preprocess a source file
uNext/Core.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Core.cpp.i
.PHONY : uNext/Core.cpp.i

uNext/Core.s: uNext/Core.cpp.s

.PHONY : uNext/Core.s

# target to generate assembly for a file
uNext/Core.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Core.cpp.s
.PHONY : uNext/Core.cpp.s

uNext/Event.obj: uNext/Event.cpp.obj

.PHONY : uNext/Event.obj

# target to build an object file
uNext/Event.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Event.cpp.obj
.PHONY : uNext/Event.cpp.obj

uNext/Event.i: uNext/Event.cpp.i

.PHONY : uNext/Event.i

# target to preprocess a source file
uNext/Event.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Event.cpp.i
.PHONY : uNext/Event.cpp.i

uNext/Event.s: uNext/Event.cpp.s

.PHONY : uNext/Event.s

# target to generate assembly for a file
uNext/Event.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Event.cpp.s
.PHONY : uNext/Event.cpp.s

uNext/Fire.obj: uNext/Fire.cpp.obj

.PHONY : uNext/Fire.obj

# target to build an object file
uNext/Fire.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Fire.cpp.obj
.PHONY : uNext/Fire.cpp.obj

uNext/Fire.i: uNext/Fire.cpp.i

.PHONY : uNext/Fire.i

# target to preprocess a source file
uNext/Fire.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Fire.cpp.i
.PHONY : uNext/Fire.cpp.i

uNext/Fire.s: uNext/Fire.cpp.s

.PHONY : uNext/Fire.s

# target to generate assembly for a file
uNext/Fire.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Fire.cpp.s
.PHONY : uNext/Fire.cpp.s

uNext/Fireball.obj: uNext/Fireball.cpp.obj

.PHONY : uNext/Fireball.obj

# target to build an object file
uNext/Fireball.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Fireball.cpp.obj
.PHONY : uNext/Fireball.cpp.obj

uNext/Fireball.i: uNext/Fireball.cpp.i

.PHONY : uNext/Fireball.i

# target to preprocess a source file
uNext/Fireball.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Fireball.cpp.i
.PHONY : uNext/Fireball.cpp.i

uNext/Fireball.s: uNext/Fireball.cpp.s

.PHONY : uNext/Fireball.s

# target to generate assembly for a file
uNext/Fireball.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Fireball.cpp.s
.PHONY : uNext/Fireball.cpp.s

uNext/Flag.obj: uNext/Flag.cpp.obj

.PHONY : uNext/Flag.obj

# target to build an object file
uNext/Flag.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Flag.cpp.obj
.PHONY : uNext/Flag.cpp.obj

uNext/Flag.i: uNext/Flag.cpp.i

.PHONY : uNext/Flag.i

# target to preprocess a source file
uNext/Flag.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Flag.cpp.i
.PHONY : uNext/Flag.cpp.i

uNext/Flag.s: uNext/Flag.cpp.s

.PHONY : uNext/Flag.s

# target to generate assembly for a file
uNext/Flag.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Flag.cpp.s
.PHONY : uNext/Flag.cpp.s

uNext/Flower.obj: uNext/Flower.cpp.obj

.PHONY : uNext/Flower.obj

# target to build an object file
uNext/Flower.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Flower.cpp.obj
.PHONY : uNext/Flower.cpp.obj

uNext/Flower.i: uNext/Flower.cpp.i

.PHONY : uNext/Flower.i

# target to preprocess a source file
uNext/Flower.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Flower.cpp.i
.PHONY : uNext/Flower.cpp.i

uNext/Flower.s: uNext/Flower.cpp.s

.PHONY : uNext/Flower.s

# target to generate assembly for a file
uNext/Flower.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Flower.cpp.s
.PHONY : uNext/Flower.cpp.s

uNext/Goombas.obj: uNext/Goombas.cpp.obj

.PHONY : uNext/Goombas.obj

# target to build an object file
uNext/Goombas.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Goombas.cpp.obj
.PHONY : uNext/Goombas.cpp.obj

uNext/Goombas.i: uNext/Goombas.cpp.i

.PHONY : uNext/Goombas.i

# target to preprocess a source file
uNext/Goombas.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Goombas.cpp.i
.PHONY : uNext/Goombas.cpp.i

uNext/Goombas.s: uNext/Goombas.cpp.s

.PHONY : uNext/Goombas.s

# target to generate assembly for a file
uNext/Goombas.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Goombas.cpp.s
.PHONY : uNext/Goombas.cpp.s

uNext/Hammer.obj: uNext/Hammer.cpp.obj

.PHONY : uNext/Hammer.obj

# target to build an object file
uNext/Hammer.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Hammer.cpp.obj
.PHONY : uNext/Hammer.cpp.obj

uNext/Hammer.i: uNext/Hammer.cpp.i

.PHONY : uNext/Hammer.i

# target to preprocess a source file
uNext/Hammer.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Hammer.cpp.i
.PHONY : uNext/Hammer.cpp.i

uNext/Hammer.s: uNext/Hammer.cpp.s

.PHONY : uNext/Hammer.s

# target to generate assembly for a file
uNext/Hammer.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Hammer.cpp.s
.PHONY : uNext/Hammer.cpp.s

uNext/HammerBro.obj: uNext/HammerBro.cpp.obj

.PHONY : uNext/HammerBro.obj

# target to build an object file
uNext/HammerBro.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/HammerBro.cpp.obj
.PHONY : uNext/HammerBro.cpp.obj

uNext/HammerBro.i: uNext/HammerBro.cpp.i

.PHONY : uNext/HammerBro.i

# target to preprocess a source file
uNext/HammerBro.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/HammerBro.cpp.i
.PHONY : uNext/HammerBro.cpp.i

uNext/HammerBro.s: uNext/HammerBro.cpp.s

.PHONY : uNext/HammerBro.s

# target to generate assembly for a file
uNext/HammerBro.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/HammerBro.cpp.s
.PHONY : uNext/HammerBro.cpp.s

uNext/IMG.obj: uNext/IMG.cpp.obj

.PHONY : uNext/IMG.obj

# target to build an object file
uNext/IMG.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/IMG.cpp.obj
.PHONY : uNext/IMG.cpp.obj

uNext/IMG.i: uNext/IMG.cpp.i

.PHONY : uNext/IMG.i

# target to preprocess a source file
uNext/IMG.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/IMG.cpp.i
.PHONY : uNext/IMG.cpp.i

uNext/IMG.s: uNext/IMG.cpp.s

.PHONY : uNext/IMG.s

# target to generate assembly for a file
uNext/IMG.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/IMG.cpp.s
.PHONY : uNext/IMG.cpp.s

uNext/Koppa.obj: uNext/Koppa.cpp.obj

.PHONY : uNext/Koppa.obj

# target to build an object file
uNext/Koppa.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Koppa.cpp.obj
.PHONY : uNext/Koppa.cpp.obj

uNext/Koppa.i: uNext/Koppa.cpp.i

.PHONY : uNext/Koppa.i

# target to preprocess a source file
uNext/Koppa.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Koppa.cpp.i
.PHONY : uNext/Koppa.cpp.i

uNext/Koppa.s: uNext/Koppa.cpp.s

.PHONY : uNext/Koppa.s

# target to generate assembly for a file
uNext/Koppa.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Koppa.cpp.s
.PHONY : uNext/Koppa.cpp.s

uNext/Lakito.obj: uNext/Lakito.cpp.obj

.PHONY : uNext/Lakito.obj

# target to build an object file
uNext/Lakito.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Lakito.cpp.obj
.PHONY : uNext/Lakito.cpp.obj

uNext/Lakito.i: uNext/Lakito.cpp.i

.PHONY : uNext/Lakito.i

# target to preprocess a source file
uNext/Lakito.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Lakito.cpp.i
.PHONY : uNext/Lakito.cpp.i

uNext/Lakito.s: uNext/Lakito.cpp.s

.PHONY : uNext/Lakito.s

# target to generate assembly for a file
uNext/Lakito.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Lakito.cpp.s
.PHONY : uNext/Lakito.cpp.s

uNext/LevelEditor.obj: uNext/LevelEditor.cpp.obj

.PHONY : uNext/LevelEditor.obj

# target to build an object file
uNext/LevelEditor.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LevelEditor.cpp.obj
.PHONY : uNext/LevelEditor.cpp.obj

uNext/LevelEditor.i: uNext/LevelEditor.cpp.i

.PHONY : uNext/LevelEditor.i

# target to preprocess a source file
uNext/LevelEditor.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LevelEditor.cpp.i
.PHONY : uNext/LevelEditor.cpp.i

uNext/LevelEditor.s: uNext/LevelEditor.cpp.s

.PHONY : uNext/LevelEditor.s

# target to generate assembly for a file
uNext/LevelEditor.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LevelEditor.cpp.s
.PHONY : uNext/LevelEditor.cpp.s

uNext/LevelText.obj: uNext/LevelText.cpp.obj

.PHONY : uNext/LevelText.obj

# target to build an object file
uNext/LevelText.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LevelText.cpp.obj
.PHONY : uNext/LevelText.cpp.obj

uNext/LevelText.i: uNext/LevelText.cpp.i

.PHONY : uNext/LevelText.i

# target to preprocess a source file
uNext/LevelText.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LevelText.cpp.i
.PHONY : uNext/LevelText.cpp.i

uNext/LevelText.s: uNext/LevelText.cpp.s

.PHONY : uNext/LevelText.s

# target to generate assembly for a file
uNext/LevelText.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LevelText.cpp.s
.PHONY : uNext/LevelText.cpp.s

uNext/LoadingMenu.obj: uNext/LoadingMenu.cpp.obj

.PHONY : uNext/LoadingMenu.obj

# target to build an object file
uNext/LoadingMenu.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LoadingMenu.cpp.obj
.PHONY : uNext/LoadingMenu.cpp.obj

uNext/LoadingMenu.i: uNext/LoadingMenu.cpp.i

.PHONY : uNext/LoadingMenu.i

# target to preprocess a source file
uNext/LoadingMenu.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LoadingMenu.cpp.i
.PHONY : uNext/LoadingMenu.cpp.i

uNext/LoadingMenu.s: uNext/LoadingMenu.cpp.s

.PHONY : uNext/LoadingMenu.s

# target to generate assembly for a file
uNext/LoadingMenu.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/LoadingMenu.cpp.s
.PHONY : uNext/LoadingMenu.cpp.s

uNext/MainMenu.obj: uNext/MainMenu.cpp.obj

.PHONY : uNext/MainMenu.obj

# target to build an object file
uNext/MainMenu.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MainMenu.cpp.obj
.PHONY : uNext/MainMenu.cpp.obj

uNext/MainMenu.i: uNext/MainMenu.cpp.i

.PHONY : uNext/MainMenu.i

# target to preprocess a source file
uNext/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MainMenu.cpp.i
.PHONY : uNext/MainMenu.cpp.i

uNext/MainMenu.s: uNext/MainMenu.cpp.s

.PHONY : uNext/MainMenu.s

# target to generate assembly for a file
uNext/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MainMenu.cpp.s
.PHONY : uNext/MainMenu.cpp.s

uNext/Map.obj: uNext/Map.cpp.obj

.PHONY : uNext/Map.obj

# target to build an object file
uNext/Map.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Map.cpp.obj
.PHONY : uNext/Map.cpp.obj

uNext/Map.i: uNext/Map.cpp.i

.PHONY : uNext/Map.i

# target to preprocess a source file
uNext/Map.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Map.cpp.i
.PHONY : uNext/Map.cpp.i

uNext/Map.s: uNext/Map.cpp.s

.PHONY : uNext/Map.s

# target to generate assembly for a file
uNext/Map.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Map.cpp.s
.PHONY : uNext/Map.cpp.s

uNext/MapLevel.obj: uNext/MapLevel.cpp.obj

.PHONY : uNext/MapLevel.obj

# target to build an object file
uNext/MapLevel.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MapLevel.cpp.obj
.PHONY : uNext/MapLevel.cpp.obj

uNext/MapLevel.i: uNext/MapLevel.cpp.i

.PHONY : uNext/MapLevel.i

# target to preprocess a source file
uNext/MapLevel.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MapLevel.cpp.i
.PHONY : uNext/MapLevel.cpp.i

uNext/MapLevel.s: uNext/MapLevel.cpp.s

.PHONY : uNext/MapLevel.s

# target to generate assembly for a file
uNext/MapLevel.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MapLevel.cpp.s
.PHONY : uNext/MapLevel.cpp.s

uNext/Menu.obj: uNext/Menu.cpp.obj

.PHONY : uNext/Menu.obj

# target to build an object file
uNext/Menu.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Menu.cpp.obj
.PHONY : uNext/Menu.cpp.obj

uNext/Menu.i: uNext/Menu.cpp.i

.PHONY : uNext/Menu.i

# target to preprocess a source file
uNext/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Menu.cpp.i
.PHONY : uNext/Menu.cpp.i

uNext/Menu.s: uNext/Menu.cpp.s

.PHONY : uNext/Menu.s

# target to generate assembly for a file
uNext/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Menu.cpp.s
.PHONY : uNext/Menu.cpp.s

uNext/MenuManager.obj: uNext/MenuManager.cpp.obj

.PHONY : uNext/MenuManager.obj

# target to build an object file
uNext/MenuManager.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MenuManager.cpp.obj
.PHONY : uNext/MenuManager.cpp.obj

uNext/MenuManager.i: uNext/MenuManager.cpp.i

.PHONY : uNext/MenuManager.i

# target to preprocess a source file
uNext/MenuManager.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MenuManager.cpp.i
.PHONY : uNext/MenuManager.cpp.i

uNext/MenuManager.s: uNext/MenuManager.cpp.s

.PHONY : uNext/MenuManager.s

# target to generate assembly for a file
uNext/MenuManager.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MenuManager.cpp.s
.PHONY : uNext/MenuManager.cpp.s

uNext/MenuOption.obj: uNext/MenuOption.cpp.obj

.PHONY : uNext/MenuOption.obj

# target to build an object file
uNext/MenuOption.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MenuOption.cpp.obj
.PHONY : uNext/MenuOption.cpp.obj

uNext/MenuOption.i: uNext/MenuOption.cpp.i

.PHONY : uNext/MenuOption.i

# target to preprocess a source file
uNext/MenuOption.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MenuOption.cpp.i
.PHONY : uNext/MenuOption.cpp.i

uNext/MenuOption.s: uNext/MenuOption.cpp.s

.PHONY : uNext/MenuOption.s

# target to generate assembly for a file
uNext/MenuOption.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MenuOption.cpp.s
.PHONY : uNext/MenuOption.cpp.s

uNext/Minion.obj: uNext/Minion.cpp.obj

.PHONY : uNext/Minion.obj

# target to build an object file
uNext/Minion.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Minion.cpp.obj
.PHONY : uNext/Minion.cpp.obj

uNext/Minion.i: uNext/Minion.cpp.i

.PHONY : uNext/Minion.i

# target to preprocess a source file
uNext/Minion.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Minion.cpp.i
.PHONY : uNext/Minion.cpp.i

uNext/Minion.s: uNext/Minion.cpp.s

.PHONY : uNext/Minion.s

# target to generate assembly for a file
uNext/Minion.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Minion.cpp.s
.PHONY : uNext/Minion.cpp.s

uNext/Mushroom.obj: uNext/Mushroom.cpp.obj

.PHONY : uNext/Mushroom.obj

# target to build an object file
uNext/Mushroom.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Mushroom.cpp.obj
.PHONY : uNext/Mushroom.cpp.obj

uNext/Mushroom.i: uNext/Mushroom.cpp.i

.PHONY : uNext/Mushroom.i

# target to preprocess a source file
uNext/Mushroom.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Mushroom.cpp.i
.PHONY : uNext/Mushroom.cpp.i

uNext/Mushroom.s: uNext/Mushroom.cpp.s

.PHONY : uNext/Mushroom.s

# target to generate assembly for a file
uNext/Mushroom.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Mushroom.cpp.s
.PHONY : uNext/Mushroom.cpp.s

uNext/Music.obj: uNext/Music.cpp.obj

.PHONY : uNext/Music.obj

# target to build an object file
uNext/Music.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Music.cpp.obj
.PHONY : uNext/Music.cpp.obj

uNext/Music.i: uNext/Music.cpp.i

.PHONY : uNext/Music.i

# target to preprocess a source file
uNext/Music.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Music.cpp.i
.PHONY : uNext/Music.cpp.i

uNext/Music.s: uNext/Music.cpp.s

.PHONY : uNext/Music.s

# target to generate assembly for a file
uNext/Music.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Music.cpp.s
.PHONY : uNext/Music.cpp.s

uNext/MusicManager.obj: uNext/MusicManager.cpp.obj

.PHONY : uNext/MusicManager.obj

# target to build an object file
uNext/MusicManager.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MusicManager.cpp.obj
.PHONY : uNext/MusicManager.cpp.obj

uNext/MusicManager.i: uNext/MusicManager.cpp.i

.PHONY : uNext/MusicManager.i

# target to preprocess a source file
uNext/MusicManager.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MusicManager.cpp.i
.PHONY : uNext/MusicManager.cpp.i

uNext/MusicManager.s: uNext/MusicManager.cpp.s

.PHONY : uNext/MusicManager.s

# target to generate assembly for a file
uNext/MusicManager.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/MusicManager.cpp.s
.PHONY : uNext/MusicManager.cpp.s

uNext/OptionsMenu.obj: uNext/OptionsMenu.cpp.obj

.PHONY : uNext/OptionsMenu.obj

# target to build an object file
uNext/OptionsMenu.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/OptionsMenu.cpp.obj
.PHONY : uNext/OptionsMenu.cpp.obj

uNext/OptionsMenu.i: uNext/OptionsMenu.cpp.i

.PHONY : uNext/OptionsMenu.i

# target to preprocess a source file
uNext/OptionsMenu.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/OptionsMenu.cpp.i
.PHONY : uNext/OptionsMenu.cpp.i

uNext/OptionsMenu.s: uNext/OptionsMenu.cpp.s

.PHONY : uNext/OptionsMenu.s

# target to generate assembly for a file
uNext/OptionsMenu.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/OptionsMenu.cpp.s
.PHONY : uNext/OptionsMenu.cpp.s

uNext/PauseMenu.obj: uNext/PauseMenu.cpp.obj

.PHONY : uNext/PauseMenu.obj

# target to build an object file
uNext/PauseMenu.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/PauseMenu.cpp.obj
.PHONY : uNext/PauseMenu.cpp.obj

uNext/PauseMenu.i: uNext/PauseMenu.cpp.i

.PHONY : uNext/PauseMenu.i

# target to preprocess a source file
uNext/PauseMenu.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/PauseMenu.cpp.i
.PHONY : uNext/PauseMenu.cpp.i

uNext/PauseMenu.s: uNext/PauseMenu.cpp.s

.PHONY : uNext/PauseMenu.s

# target to generate assembly for a file
uNext/PauseMenu.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/PauseMenu.cpp.s
.PHONY : uNext/PauseMenu.cpp.s

uNext/Pipe.obj: uNext/Pipe.cpp.obj

.PHONY : uNext/Pipe.obj

# target to build an object file
uNext/Pipe.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Pipe.cpp.obj
.PHONY : uNext/Pipe.cpp.obj

uNext/Pipe.i: uNext/Pipe.cpp.i

.PHONY : uNext/Pipe.i

# target to preprocess a source file
uNext/Pipe.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Pipe.cpp.i
.PHONY : uNext/Pipe.cpp.i

uNext/Pipe.s: uNext/Pipe.cpp.s

.PHONY : uNext/Pipe.s

# target to generate assembly for a file
uNext/Pipe.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Pipe.cpp.s
.PHONY : uNext/Pipe.cpp.s

uNext/Plant.obj: uNext/Plant.cpp.obj

.PHONY : uNext/Plant.obj

# target to build an object file
uNext/Plant.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Plant.cpp.obj
.PHONY : uNext/Plant.cpp.obj

uNext/Plant.i: uNext/Plant.cpp.i

.PHONY : uNext/Plant.i

# target to preprocess a source file
uNext/Plant.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Plant.cpp.i
.PHONY : uNext/Plant.cpp.i

uNext/Plant.s: uNext/Plant.cpp.s

.PHONY : uNext/Plant.s

# target to generate assembly for a file
uNext/Plant.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Plant.cpp.s
.PHONY : uNext/Plant.cpp.s

uNext/Platform.obj: uNext/Platform.cpp.obj

.PHONY : uNext/Platform.obj

# target to build an object file
uNext/Platform.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Platform.cpp.obj
.PHONY : uNext/Platform.cpp.obj

uNext/Platform.i: uNext/Platform.cpp.i

.PHONY : uNext/Platform.i

# target to preprocess a source file
uNext/Platform.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Platform.cpp.i
.PHONY : uNext/Platform.cpp.i

uNext/Platform.s: uNext/Platform.cpp.s

.PHONY : uNext/Platform.s

# target to generate assembly for a file
uNext/Platform.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Platform.cpp.s
.PHONY : uNext/Platform.cpp.s

uNext/Player.obj: uNext/Player.cpp.obj

.PHONY : uNext/Player.obj

# target to build an object file
uNext/Player.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Player.cpp.obj
.PHONY : uNext/Player.cpp.obj

uNext/Player.i: uNext/Player.cpp.i

.PHONY : uNext/Player.i

# target to preprocess a source file
uNext/Player.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Player.cpp.i
.PHONY : uNext/Player.cpp.i

uNext/Player.s: uNext/Player.cpp.s

.PHONY : uNext/Player.s

# target to generate assembly for a file
uNext/Player.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Player.cpp.s
.PHONY : uNext/Player.cpp.s

uNext/PlayerFireBall.obj: uNext/PlayerFireBall.cpp.obj

.PHONY : uNext/PlayerFireBall.obj

# target to build an object file
uNext/PlayerFireBall.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/PlayerFireBall.cpp.obj
.PHONY : uNext/PlayerFireBall.cpp.obj

uNext/PlayerFireBall.i: uNext/PlayerFireBall.cpp.i

.PHONY : uNext/PlayerFireBall.i

# target to preprocess a source file
uNext/PlayerFireBall.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/PlayerFireBall.cpp.i
.PHONY : uNext/PlayerFireBall.cpp.i

uNext/PlayerFireBall.s: uNext/PlayerFireBall.cpp.s

.PHONY : uNext/PlayerFireBall.s

# target to generate assembly for a file
uNext/PlayerFireBall.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/PlayerFireBall.cpp.s
.PHONY : uNext/PlayerFireBall.cpp.s

uNext/Points.obj: uNext/Points.cpp.obj

.PHONY : uNext/Points.obj

# target to build an object file
uNext/Points.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Points.cpp.obj
.PHONY : uNext/Points.cpp.obj

uNext/Points.i: uNext/Points.cpp.i

.PHONY : uNext/Points.i

# target to preprocess a source file
uNext/Points.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Points.cpp.i
.PHONY : uNext/Points.cpp.i

uNext/Points.s: uNext/Points.cpp.s

.PHONY : uNext/Points.s

# target to generate assembly for a file
uNext/Points.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Points.cpp.s
.PHONY : uNext/Points.cpp.s

uNext/Spikey.obj: uNext/Spikey.cpp.obj

.PHONY : uNext/Spikey.obj

# target to build an object file
uNext/Spikey.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Spikey.cpp.obj
.PHONY : uNext/Spikey.cpp.obj

uNext/Spikey.i: uNext/Spikey.cpp.i

.PHONY : uNext/Spikey.i

# target to preprocess a source file
uNext/Spikey.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Spikey.cpp.i
.PHONY : uNext/Spikey.cpp.i

uNext/Spikey.s: uNext/Spikey.cpp.s

.PHONY : uNext/Spikey.s

# target to generate assembly for a file
uNext/Spikey.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Spikey.cpp.s
.PHONY : uNext/Spikey.cpp.s

uNext/Spring.obj: uNext/Spring.cpp.obj

.PHONY : uNext/Spring.obj

# target to build an object file
uNext/Spring.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Spring.cpp.obj
.PHONY : uNext/Spring.cpp.obj

uNext/Spring.i: uNext/Spring.cpp.i

.PHONY : uNext/Spring.i

# target to preprocess a source file
uNext/Spring.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Spring.cpp.i
.PHONY : uNext/Spring.cpp.i

uNext/Spring.s: uNext/Spring.cpp.s

.PHONY : uNext/Spring.s

# target to generate assembly for a file
uNext/Spring.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Spring.cpp.s
.PHONY : uNext/Spring.cpp.s

uNext/Sprite.obj: uNext/Sprite.cpp.obj

.PHONY : uNext/Sprite.obj

# target to build an object file
uNext/Sprite.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Sprite.cpp.obj
.PHONY : uNext/Sprite.cpp.obj

uNext/Sprite.i: uNext/Sprite.cpp.i

.PHONY : uNext/Sprite.i

# target to preprocess a source file
uNext/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Sprite.cpp.i
.PHONY : uNext/Sprite.cpp.i

uNext/Sprite.s: uNext/Sprite.cpp.s

.PHONY : uNext/Sprite.s

# target to generate assembly for a file
uNext/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Sprite.cpp.s
.PHONY : uNext/Sprite.cpp.s

uNext/Squid.obj: uNext/Squid.cpp.obj

.PHONY : uNext/Squid.obj

# target to build an object file
uNext/Squid.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Squid.cpp.obj
.PHONY : uNext/Squid.cpp.obj

uNext/Squid.i: uNext/Squid.cpp.i

.PHONY : uNext/Squid.i

# target to preprocess a source file
uNext/Squid.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Squid.cpp.i
.PHONY : uNext/Squid.cpp.i

uNext/Squid.s: uNext/Squid.cpp.s

.PHONY : uNext/Squid.s

# target to generate assembly for a file
uNext/Squid.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Squid.cpp.s
.PHONY : uNext/Squid.cpp.s

uNext/Star.obj: uNext/Star.cpp.obj

.PHONY : uNext/Star.obj

# target to build an object file
uNext/Star.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Star.cpp.obj
.PHONY : uNext/Star.cpp.obj

uNext/Star.i: uNext/Star.cpp.i

.PHONY : uNext/Star.i

# target to preprocess a source file
uNext/Star.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Star.cpp.i
.PHONY : uNext/Star.cpp.i

uNext/Star.s: uNext/Star.cpp.s

.PHONY : uNext/Star.s

# target to generate assembly for a file
uNext/Star.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Star.cpp.s
.PHONY : uNext/Star.cpp.s

uNext/Text.obj: uNext/Text.cpp.obj

.PHONY : uNext/Text.obj

# target to build an object file
uNext/Text.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Text.cpp.obj
.PHONY : uNext/Text.cpp.obj

uNext/Text.i: uNext/Text.cpp.i

.PHONY : uNext/Text.i

# target to preprocess a source file
uNext/Text.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Text.cpp.i
.PHONY : uNext/Text.cpp.i

uNext/Text.s: uNext/Text.cpp.s

.PHONY : uNext/Text.s

# target to generate assembly for a file
uNext/Text.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Text.cpp.s
.PHONY : uNext/Text.cpp.s

uNext/Texture.obj: uNext/Texture.cpp.obj

.PHONY : uNext/Texture.obj

# target to build an object file
uNext/Texture.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Texture.cpp.obj
.PHONY : uNext/Texture.cpp.obj

uNext/Texture.i: uNext/Texture.cpp.i

.PHONY : uNext/Texture.i

# target to preprocess a source file
uNext/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Texture.cpp.i
.PHONY : uNext/Texture.cpp.i

uNext/Texture.s: uNext/Texture.cpp.s

.PHONY : uNext/Texture.s

# target to generate assembly for a file
uNext/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Texture.cpp.s
.PHONY : uNext/Texture.cpp.s

uNext/Toad.obj: uNext/Toad.cpp.obj

.PHONY : uNext/Toad.obj

# target to build an object file
uNext/Toad.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Toad.cpp.obj
.PHONY : uNext/Toad.cpp.obj

uNext/Toad.i: uNext/Toad.cpp.i

.PHONY : uNext/Toad.i

# target to preprocess a source file
uNext/Toad.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Toad.cpp.i
.PHONY : uNext/Toad.cpp.i

uNext/Toad.s: uNext/Toad.cpp.s

.PHONY : uNext/Toad.s

# target to generate assembly for a file
uNext/Toad.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Toad.cpp.s
.PHONY : uNext/Toad.cpp.s

uNext/UpFire.obj: uNext/UpFire.cpp.obj

.PHONY : uNext/UpFire.obj

# target to build an object file
uNext/UpFire.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/UpFire.cpp.obj
.PHONY : uNext/UpFire.cpp.obj

uNext/UpFire.i: uNext/UpFire.cpp.i

.PHONY : uNext/UpFire.i

# target to preprocess a source file
uNext/UpFire.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/UpFire.cpp.i
.PHONY : uNext/UpFire.cpp.i

uNext/UpFire.s: uNext/UpFire.cpp.s

.PHONY : uNext/UpFire.s

# target to generate assembly for a file
uNext/UpFire.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/UpFire.cpp.s
.PHONY : uNext/UpFire.cpp.s

uNext/Vector2.obj: uNext/Vector2.cpp.obj

.PHONY : uNext/Vector2.obj

# target to build an object file
uNext/Vector2.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Vector2.cpp.obj
.PHONY : uNext/Vector2.cpp.obj

uNext/Vector2.i: uNext/Vector2.cpp.i

.PHONY : uNext/Vector2.i

# target to preprocess a source file
uNext/Vector2.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Vector2.cpp.i
.PHONY : uNext/Vector2.cpp.i

uNext/Vector2.s: uNext/Vector2.cpp.s

.PHONY : uNext/Vector2.s

# target to generate assembly for a file
uNext/Vector2.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Vector2.cpp.s
.PHONY : uNext/Vector2.cpp.s

uNext/Vine.obj: uNext/Vine.cpp.obj

.PHONY : uNext/Vine.obj

# target to build an object file
uNext/Vine.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Vine.cpp.obj
.PHONY : uNext/Vine.cpp.obj

uNext/Vine.i: uNext/Vine.cpp.i

.PHONY : uNext/Vine.i

# target to preprocess a source file
uNext/Vine.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Vine.cpp.i
.PHONY : uNext/Vine.cpp.i

uNext/Vine.s: uNext/Vine.cpp.s

.PHONY : uNext/Vine.s

# target to generate assembly for a file
uNext/Vine.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/Vine.cpp.s
.PHONY : uNext/Vine.cpp.s

uNext/main.obj: uNext/main.cpp.obj

.PHONY : uNext/main.obj

# target to build an object file
uNext/main.cpp.obj:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/main.cpp.obj
.PHONY : uNext/main.cpp.obj

uNext/main.i: uNext/main.cpp.i

.PHONY : uNext/main.i

# target to preprocess a source file
uNext/main.cpp.i:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/main.cpp.i
.PHONY : uNext/main.cpp.i

uNext/main.s: uNext/main.cpp.s

.PHONY : uNext/main.s

# target to generate assembly for a file
uNext/main.cpp.s:
	$(MAKE) -f CMakeFiles/uMario.dir/build.make CMakeFiles/uMario.dir/uNext/main.cpp.s
.PHONY : uNext/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... uMario.vpk"
	@echo "... uMario.self"
	@echo "... uMario"
	@echo "... uNext/AboutMenu.obj"
	@echo "... uNext/AboutMenu.i"
	@echo "... uNext/AboutMenu.s"
	@echo "... uNext/Beetle.obj"
	@echo "... uNext/Beetle.i"
	@echo "... uNext/Beetle.s"
	@echo "... uNext/Block.obj"
	@echo "... uNext/Block.i"
	@echo "... uNext/Block.s"
	@echo "... uNext/BlockDebris.obj"
	@echo "... uNext/BlockDebris.i"
	@echo "... uNext/BlockDebris.s"
	@echo "... uNext/Bowser.obj"
	@echo "... uNext/Bowser.i"
	@echo "... uNext/Bowser.s"
	@echo "... uNext/Bubble.obj"
	@echo "... uNext/Bubble.i"
	@echo "... uNext/Bubble.s"
	@echo "... uNext/BulletBill.obj"
	@echo "... uNext/BulletBill.i"
	@echo "... uNext/BulletBill.s"
	@echo "... uNext/BulletBillSpawner.obj"
	@echo "... uNext/BulletBillSpawner.i"
	@echo "... uNext/BulletBillSpawner.s"
	@echo "... uNext/CFG.obj"
	@echo "... uNext/CFG.i"
	@echo "... uNext/CFG.s"
	@echo "... uNext/Cheep.obj"
	@echo "... uNext/Cheep.i"
	@echo "... uNext/Cheep.s"
	@echo "... uNext/CheepSpawner.obj"
	@echo "... uNext/CheepSpawner.i"
	@echo "... uNext/CheepSpawner.s"
	@echo "... uNext/Coin.obj"
	@echo "... uNext/Coin.i"
	@echo "... uNext/Coin.s"
	@echo "... uNext/Console.obj"
	@echo "... uNext/Console.i"
	@echo "... uNext/Console.s"
	@echo "... uNext/Core.obj"
	@echo "... uNext/Core.i"
	@echo "... uNext/Core.s"
	@echo "... uNext/Event.obj"
	@echo "... uNext/Event.i"
	@echo "... uNext/Event.s"
	@echo "... uNext/Fire.obj"
	@echo "... uNext/Fire.i"
	@echo "... uNext/Fire.s"
	@echo "... uNext/Fireball.obj"
	@echo "... uNext/Fireball.i"
	@echo "... uNext/Fireball.s"
	@echo "... uNext/Flag.obj"
	@echo "... uNext/Flag.i"
	@echo "... uNext/Flag.s"
	@echo "... uNext/Flower.obj"
	@echo "... uNext/Flower.i"
	@echo "... uNext/Flower.s"
	@echo "... uNext/Goombas.obj"
	@echo "... uNext/Goombas.i"
	@echo "... uNext/Goombas.s"
	@echo "... uNext/Hammer.obj"
	@echo "... uNext/Hammer.i"
	@echo "... uNext/Hammer.s"
	@echo "... uNext/HammerBro.obj"
	@echo "... uNext/HammerBro.i"
	@echo "... uNext/HammerBro.s"
	@echo "... uNext/IMG.obj"
	@echo "... uNext/IMG.i"
	@echo "... uNext/IMG.s"
	@echo "... uNext/Koppa.obj"
	@echo "... uNext/Koppa.i"
	@echo "... uNext/Koppa.s"
	@echo "... uNext/Lakito.obj"
	@echo "... uNext/Lakito.i"
	@echo "... uNext/Lakito.s"
	@echo "... uNext/LevelEditor.obj"
	@echo "... uNext/LevelEditor.i"
	@echo "... uNext/LevelEditor.s"
	@echo "... uNext/LevelText.obj"
	@echo "... uNext/LevelText.i"
	@echo "... uNext/LevelText.s"
	@echo "... uNext/LoadingMenu.obj"
	@echo "... uNext/LoadingMenu.i"
	@echo "... uNext/LoadingMenu.s"
	@echo "... uNext/MainMenu.obj"
	@echo "... uNext/MainMenu.i"
	@echo "... uNext/MainMenu.s"
	@echo "... uNext/Map.obj"
	@echo "... uNext/Map.i"
	@echo "... uNext/Map.s"
	@echo "... uNext/MapLevel.obj"
	@echo "... uNext/MapLevel.i"
	@echo "... uNext/MapLevel.s"
	@echo "... uNext/Menu.obj"
	@echo "... uNext/Menu.i"
	@echo "... uNext/Menu.s"
	@echo "... uNext/MenuManager.obj"
	@echo "... uNext/MenuManager.i"
	@echo "... uNext/MenuManager.s"
	@echo "... uNext/MenuOption.obj"
	@echo "... uNext/MenuOption.i"
	@echo "... uNext/MenuOption.s"
	@echo "... uNext/Minion.obj"
	@echo "... uNext/Minion.i"
	@echo "... uNext/Minion.s"
	@echo "... uNext/Mushroom.obj"
	@echo "... uNext/Mushroom.i"
	@echo "... uNext/Mushroom.s"
	@echo "... uNext/Music.obj"
	@echo "... uNext/Music.i"
	@echo "... uNext/Music.s"
	@echo "... uNext/MusicManager.obj"
	@echo "... uNext/MusicManager.i"
	@echo "... uNext/MusicManager.s"
	@echo "... uNext/OptionsMenu.obj"
	@echo "... uNext/OptionsMenu.i"
	@echo "... uNext/OptionsMenu.s"
	@echo "... uNext/PauseMenu.obj"
	@echo "... uNext/PauseMenu.i"
	@echo "... uNext/PauseMenu.s"
	@echo "... uNext/Pipe.obj"
	@echo "... uNext/Pipe.i"
	@echo "... uNext/Pipe.s"
	@echo "... uNext/Plant.obj"
	@echo "... uNext/Plant.i"
	@echo "... uNext/Plant.s"
	@echo "... uNext/Platform.obj"
	@echo "... uNext/Platform.i"
	@echo "... uNext/Platform.s"
	@echo "... uNext/Player.obj"
	@echo "... uNext/Player.i"
	@echo "... uNext/Player.s"
	@echo "... uNext/PlayerFireBall.obj"
	@echo "... uNext/PlayerFireBall.i"
	@echo "... uNext/PlayerFireBall.s"
	@echo "... uNext/Points.obj"
	@echo "... uNext/Points.i"
	@echo "... uNext/Points.s"
	@echo "... uNext/Spikey.obj"
	@echo "... uNext/Spikey.i"
	@echo "... uNext/Spikey.s"
	@echo "... uNext/Spring.obj"
	@echo "... uNext/Spring.i"
	@echo "... uNext/Spring.s"
	@echo "... uNext/Sprite.obj"
	@echo "... uNext/Sprite.i"
	@echo "... uNext/Sprite.s"
	@echo "... uNext/Squid.obj"
	@echo "... uNext/Squid.i"
	@echo "... uNext/Squid.s"
	@echo "... uNext/Star.obj"
	@echo "... uNext/Star.i"
	@echo "... uNext/Star.s"
	@echo "... uNext/Text.obj"
	@echo "... uNext/Text.i"
	@echo "... uNext/Text.s"
	@echo "... uNext/Texture.obj"
	@echo "... uNext/Texture.i"
	@echo "... uNext/Texture.s"
	@echo "... uNext/Toad.obj"
	@echo "... uNext/Toad.i"
	@echo "... uNext/Toad.s"
	@echo "... uNext/UpFire.obj"
	@echo "... uNext/UpFire.i"
	@echo "... uNext/UpFire.s"
	@echo "... uNext/Vector2.obj"
	@echo "... uNext/Vector2.i"
	@echo "... uNext/Vector2.s"
	@echo "... uNext/Vine.obj"
	@echo "... uNext/Vine.i"
	@echo "... uNext/Vine.s"
	@echo "... uNext/main.obj"
	@echo "... uNext/main.i"
	@echo "... uNext/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

